meta:
  divergence: KL
  regularization: 0.005
  task: identity
model:
  architecture: fcn
  hidden_layers:
  - 2048
  - 2048
  - 2048
  - 2048
  - 2048
  - 2048
  - 2048
  - 2048
optim:
  amsgrad: false
  beta1: 0.9
  eps: 1.0e-08
  lr: 1.0e-05
  optimizer: Adam
  weight_decay: 0.0
source:
  data:
    channels: 2
    dataset: T1
    folder: /scratch1/04475/ajil/datasets/skm-target
    gaussian_dequantization: false
    image_size: 160
    logit_transform: false
    num_workers: 12
    random_flip: false
    rescaled: false
    uniform_dequantization: false
target:
  data:
    channels: 2
    dataset: T2
    folder: /scratch1/04475/ajil/datasets/skm-target
    gaussian_dequantization: false
    image_size: 160
    logit_transform: false
    num_workers: 12
    random_flip: false
    rescaled: false
    uniform_dequantization: false
training:
  batch_size: 1000
  n_iters: 5001
  snapshot_freq: 500
transport:
  coeff: 0.005
  cost: mean-l2-sq
  regularization: entropy

