compatibility:
  log_path: pretrained/compatibility/densities/usps_KL_0.01
  ckpt_id:
  model:
    architecture: "fcn"
    hidden_layers: [1024, 1024]

baryproj:
  log_path: pretrained/baryproj/usps_KL_0.01
  ckpt_id: # use final ckpt
  model:
    architecture: "fcn"
    hidden_layer_dims: [1024, 1024]

target:
  data:
    dataset: "USPS"
    image_size: 16
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 12

source:
  data:
    dataset: "MNIST"
    image_size: 16
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 12

transport:
  regularization: "entropy" # l2, entropy
  coeff: 0.01
  cost: "mean-l2-sq"

ncsn:
  sampling:
    log_path: pretrained/ncsn/usps_16px
    sources_per_batch: 250
    samples_per_source: 5
    data_init: true
    #step_lr: 0.0000015
    step_lr: 0.00005
    #n_steps_each: 10
    n_steps_each: 10
    ckpt_id:
    final_only: true
    fid: true
    denoise: true
    num_samples4fid: 50000
    inpainting: false
    interpolation: false
    n_interpolations: 50
    n_sigmas_skip: 3

  fast_fid:
    batch_size: 1000
    num_sources: 1000
    step_lr: 0.0000033
    n_steps_each: 5
    begin_ckpt: 5000
    end_ckpt: 210000
    verbose: false
    ensemble: false

  model:
    sigma_begin: 1
    sigma_end: 0.01
    num_classes: 10
    ema: false
    ema_rate: 0
    spec_norm: false
    sigma_dist: 'geometric'
    normalization: InstanceNorm++
    nonlinearity: elu
    ngf: 64
