compatibility:
  log_path: pretrained/compatibility/densities/mnist_chisq_0.001
  ckpt_id:
  beta: 1000
  model:
    architecture: "fcn"
    hidden_layers: [1024, 1024]

baryproj:
  log_path: pretrained/baryproj/usps_mnist_largebp
  ckpt_id: # use final ckpt
  model:
    architecture: "fcn"
    hidden_layer_dims: [2048, 2048, 2048, 2048]

source:
  data:
    dataset: "USPS"
    image_size: 16
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 12

target:
  data:
    dataset: "MNIST"
    image_size: 16
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 12

transport:
  regularization: "l2" # l2, entropy
  coeff: 0.001
  cost: "mean-l2-sq"

ncsn:
  sampling:
    log_path: pretrained/ncsn/mnist_16px
    sources_per_batch: 100 #317
    samples_per_source: 40 #5
    data_init: true
    #step_lr: 0.0000015
    step_lr: 0.00005
    #n_steps_each: 10
    n_steps_each: 10
    ckpt_id:
    final_only: true
    fid: false
    denoise: true
    num_samples4fid: 36455
    inpainting: false
    interpolation: false
    n_interpolations: 50
    n_sigmas_skip: 3

  fast_fid:
    batch_size: 1000
    num_sources: 1000
    step_lr: 0.0000033
    n_steps_each: 5
    begin_ckpt: 5000
    end_ckpt: 210000
    verbose: false
    ensemble: false

  model:
    sigma_begin: 1
    sigma_end: 0.01
    num_classes: 10
    ema: false
    ema_rate: 0
    spec_norm: false
    sigma_dist: 'geometric'
    normalization: InstanceNorm++
    nonlinearity: elu
    ngf: 64