source:
  data:
    dataset: "CELEBA"
    image_size: 64
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: false
    num_workers: 0

target:
  data:
    dataset: "CELEBA"
    image_size: 64
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: false
    num_workers: 0

transport:
  regularization: "l2" # l2, entropy
  coeff: 0.01
  cost: "mean-l2-sq" # l2-sq, mean-l2-sq

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.000001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001

model:
  architecture: "res"
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 48

training:
  batch_size: 64
  n_iters: 20000
  snapshot_freq: 5000
  sample_freq: 200

compatibility:
  log_path: pretrained/compatibility/densities/celeba_chisq_0.01
  ckpt_id: 5000
  model:
    architecture: "fcn"
    hidden_layers: [2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]

sampling:
  ckpt_id:
  samples_per_batch: 100
  fid: true
  num_samples4fid: 5000