source:
  data:
    dataset: "Gaussian"
    isotropic: true
    dim: 784
    rank: 784
    mean:
    cov:
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 0

target:
  data:
    dataset: "Gaussian-HD"
    isotropic: false
    dim: 784
    rank: 784
    mean_path: datasets/gaussian_statistics/MNIST-Mean-01.npy
    cov_path: datasets/gaussian_statistics/MNIST-Cov-01-add_0.1_noise.npy
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 0

transport:
  regularization: "entropy" # l2, entropy
  coeff: 1
  cost: "mean-l2-sq" # l2-sq, mean-l2-sq

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.00001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001

model:
  architecture: "fcn"
  hidden_layers: [2048, 2048, 2048, 2048]

training:
  batch_size: 1000
  n_iters: 5001
  snapshot_freq: 5000
