training:
  batch_size: 128
  n_epochs: 500000
  n_iters: 40001
  ngpu: 1
  snapshot_freq: 5000
  snapshot_sampling: true
  algo: 'dsm'
  anneal_power: 2.0
  log_all_sigmas: false

data:
  dataset: "MNIST"
  image_size: 16
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: false
  num_workers: 12

model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  ema: false
  ema_rate: 0
  spec_norm: false
  sigma_dist: 'geometric'
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 64

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  eps: 0.00000001
  amsgrad: false


sampling:
  batch_size: 64
  data_init: false
  #step_lr: 0.0000015
  step_lr: 0.00005
  #n_steps_each: 10
  n_steps_each: 20
  ckpt_id:
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15