compatibility:
  log_path: pretrained/compatibility/mnist_l2_r=0.001
  ckpt_id: 5000
  model:
    architecture: "fcn"
    hidden_layers: [2048, 2048, 2048, 2048]

source:
  data:
    dataset: "USPS"
    image_size: 28
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 4

target:
  data:
    dataset: "MNIST"
    image_size: 28
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 4

transport:
  regularization: "l2" # l2, entropy
  coeff: 0.005
  cost: "mean-l2-sq"

ncsn:
  sampling:
    log_path: pretrained/ncsn/mnist
    sources_per_batch: 8
    samples_per_source: 8
    data_init: true
    #step_lr: 0.0000005
    step_lr: 0.0000005
    #n_steps_each: 10
    n_steps_each: 50
    ckpt_id:
    final_only: true
    fid: false
    denoise: true
    num_samples4fid: 10000
    inpainting: false
    interpolation: false
    n_interpolations: 50

  fast_fid:
    batch_size: 1000
    num_sources: 1000
    step_lr: 0.0000033
    n_steps_each: 5
    begin_ckpt: 5000
    end_ckpt: 210000
    verbose: false
    ensemble: false

  model:
    sigma_begin: 1
    sigma_end: 0.01
    num_classes: 10
    ema: false
    ema_rate: 0
    spec_norm: false
    sigma_dist: 'geometric'
    normalization: InstanceNorm++
    nonlinearity: elu
    ngf: 64
