source:
  data:
    dataset: "USPS-Pad"
    image_size: 28
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 8

target:
  data:
    dataset: "MNIST"
    image_size: 28
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 8

transport:
  regularization: "l2" # l2, entropy
  coeff: 0.001
  cost: "mean-l2-sq" # l2-sq, mean-l2-sq

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.000005
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001

model:
  architecture: "fcn"
  hidden_layer_dims: [1000, 1000]
  #upsampler_hidden_channels: [1024, 512, 256, 128]
  #downsampler_hidden_channels: [128, 256, 512, 1024]
  #bottleneck_dim: 100

training:
  batch_size: 500
  n_iters: 10001
  snapshot_freq: 5000
  sample_freq: 100

sampling:
  batch_size: 64
  data_init: false
  #step_lr: 0.0000015
  step_lr: 0.00005
  #n_steps_each: 10
  n_steps_each: 20
  ckpt_id:
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15

compatibility:
  log_path: pretrained/compatibility/mnist_l2_r=0.001
  ckpt_id: 5000
  model:
    architecture: "fcn"
    hidden_layers: [2048, 2048, 2048, 2048]
